### ISSUE TITLE
Cooperative Groups

### ISSUE THREAD

**Issue by TalDerei** [matter-labs/era-bellman-cuda#2]
I notice in the test suite, there are 'N' total threads divided among 'G' thread blocks, with each thread performing a single operation **(e.g. ec_add, ec_sub, ec_dbl, ec_mul)** between two affine / projective points. I think it would be worth looking into cooperative groups for performing these operations using tiled partitions. Instead of single thread looping over all the limbs for a single point, multiple threads can access a different limbs (or sub-parts of the same limb) of the same point in parallel. This would naively lead to 8x speedup in low-level arithmetic operations, since you deconstruct a field element into 8 32-bit limbs. 

This would require a huge refactor of the codebase, just putting the idea out there in case it hadn't been considered: https://developer.nvidia.com/blog/cooperative-groups/

**Comment by robik75** [comment]
We already looked into this, in fact we had a working implementation of multi-threaded field operation, but in the end removed it as for our particular use case it did not offer any benefit.
Multi-thread variants of field operation have a significant data exchange overhead and would only provide benefit when we would have a lot of work with low level of parallelization potential or if we needed to work with substantially larger fields, neither of which applies in our case.
