### ISSUE TITLE
32-bit vs 64-bit limbs

### ISSUE THREAD

**Issue by TalDerei** [matter-labs/era-bellman-cuda#3]
I have a general inquiry regarding performance depending on the limb size. The register size (word width) on Nvidia GPUs is 32-bits, and 64-bit instructions are emulated with 32-bit instructions. Have you experimented with 64-bit limbs for field elements, and if so, have you experienced any sort of speedup moving to 32-bit limbs?

**Comment by TalDerei** [comment]
@robik75 Not sure if you experimented with this?

**Comment by robik75** [comment]
We did experiment with 64-bit limbs but the results were slightly slower than using 32-bit limbs.
